import test from 'node:test';
import assert from 'node:assert/strict';
import {diagnose,purchaseQuote} from '../web/sourcing-model.mjs';
import {buyDecision,sellDecisions} from '../web/market-decisions.mjs';
import {planDay,defaultSettings,remainingPurchase} from '../web/tokyo-planner.mjs';
const now=new Date('2026-10-02T10:00:00+09:00');
function item(){return {id:'x',name:'测试鞋',code:'SKU',color:'黑',size:'27',channel:'得物',source_name:'网站',source_url:'https://example.com/x',quote:{buy_jpy:10000,fx:.05,extra_cny:50,net_cny:800,units:1,target_profit:100,checked_at:'2026-10-02',evidence_at:'2026-10-02',evidence_kind:'sold',evidence:'同款成交',stock:true,delivery:true,tax:true,seller:true}};}
function auction(){const i=item();i.deal={kind:'auction',current_jpy:10000,increment_jpy:100,fee_pct:10,fixed_jpy:200,observed_at:'2026-10-02T09:55:00+09:00',ends_at:'2026-10-02T12:00:00+09:00'};return i;}
function day(){return {...defaultSettings(),date:'2026-10-02',extra_cny:0,records:[{item_id:'x',name:'测试鞋',code:'SKU',color:'黑',size:'27',channel:'得物',status:'bought',units:2,cost_cny:1000,expected_net_cny:1100,actual_net_cny:null}]};}
test('auction next bid includes both fees; ceiling is an all-cost ceiling',()=>{const d=diagnose(auction(),now);assert.equal(purchaseQuote(auction()).buy_jpy,11310);assert.equal(d.cost,615.5);assert.equal(d.maxBidJPY,11636);assert.equal(d.ready,true);});
test('unknown buyer fee never becomes zero or an actionable quote',()=>{const i=auction();i.deal.fee_pct=null;assert.equal(diagnose(i,now).cost,null);assert.equal(buyDecision(i,7000,now).state,'watch');});
test('stale auction observations, passed deadlines and future observations fail closed',()=>{for(const changes of [{observed_at:'2026-10-02T09:00:00+09:00'},{ends_at:'2026-10-02T09:59:00+09:00'},{observed_at:'2026-10-02T10:01:00+09:00'}]){const i=auction();Object.assign(i.deal,changes);assert.equal(diagnose(i,now).ready,false);assert.notEqual(buyDecision(i,7000,now).state,'buy');}});
test('a bid past the ceiling is passed even if market headline looks popular',()=>{const i=auction();i.deal.current_jpy=12000;assert.equal(buyDecision(i,7000,now).state,'pass');});
test('remaining budget constrains the buy recommendation',()=>{assert.equal(buyDecision(item(),500,now).state,'watch');assert.equal(buyDecision(item(),7000,now).state,'buy');});
test('buy decisions only price unbought target quantities and stop when fully bought',()=>{const i=item();i.quote.units=3;const r=day().records;const remaining=remainingPurchase(i,r);assert.equal(remaining.quote.units,1);assert.equal(buyDecision(remaining,600,now).state,'buy');r[0].units=3;const decision=buyDecision(remainingPurchase(i,r),7000,now);assert.equal(decision.state,'pass');assert.match(decision.reason,/已购齐/);});
test('a future release is watched, never described as buyable now',()=>{const i=item();i.deal={kind:'drop'};i.visit={release_at:'2026-10-03T10:00:00+09:00',release_source:'https://example.com/event'};assert.equal(buyDecision(i,7000,now).state,'watch');});
test('a drop without official time and source cannot be a qualified buy',()=>{const i=item();i.deal={kind:'drop'};assert.equal(diagnose(i,now).ready,false);assert.equal(buyDecision(i,7000,now).state,'watch');});
test('sell recommendation uses actual lot cost and current proceeds, not original guess',()=>{const r=sellDecisions([item()],[day()],now)[0];assert.equal(r.state,'sell');assert.equal(r.proceeds,1600);assert.equal(r.profit,600);assert.equal(r.targetNet,1200);});
test('settled records never remain in selling recommendations',()=>{const d=day();d.records[0].actual_net_cny=1500;assert.equal(sellDecisions([item()],[d],now).length,0);});
test('archiving a purchase candidate does not hide actual unsold holdings',()=>{const i=item();i.archived=true;assert.equal(sellDecisions([i],[day()],now).length,1);});
test('changed size, stale evidence, asks and missing inventory spec do not recommend sell',()=>{for(const change of ['size','stale','ask','missing']){const i=item(),d=day();if(change==='size')i.size='28';if(change==='stale')i.quote.evidence_at='2026-09-01';if(change==='ask')i.quote.evidence_kind='ask';if(change==='missing')delete d.records[0].size;const r=sellDecisions([i],[d],now)[0];assert.equal(r.state,'review');assert.equal(r.profit,null);}});
test('losing inventory is flagged without making an unsupported hold or sell call',()=>{const i=item();i.quote.net_cny=400;const r=sellDecisions([i],[day()],now)[0];assert.equal(r.state,'review');assert.equal(r.profit,-200);assert.match(r.reason,/止损/);});
test('no holdings means no sell recommendations; synthetic records are excluded',()=>{assert.deepEqual(sellDecisions([item()],[],now),[]);const d=day();d.records[0].code='TEST-PKMN-151';assert.deepEqual(sellDecisions([item()],[d],now),[]);});
test('auction already ended before travel day cannot enter the route',()=>{const i=auction(),s=day();s.date='2026-10-03';s.records=[];const p=planDay([i],s,[],[],'buy',now);assert.equal(p.items.length,0);});
